base/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate,DeleteView, CustomeLoginView, RegisterPage
from django.contrib.auth.views import LogoutView

urlpatterns=[
    path('login/',CustomeLoginView.as_view() , name='login'),
    path('logout/',LogoutView.as_view(next_page='login') , name='logout'),
    path('register/',RegisterPage.as_view() , name='register'),
    path('',TaskList.as_view() , name='tasks'),
    path('task/<int:pk>/',TaskDetail.as_view() , name='task'),
    path('task-create/',TaskCreate.as_view() , name='task-create'),
    path('task-update/<int:pk>/',TaskUpdate.as_view() , name='task-update'),
    path('task-delete/<int:pk>/',DeleteView.as_view() , name='task-delete')
    
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    High = 'H'
    Medium = 'M'
    Low = 'L'
    IMPACT_CHOICES = [
        (High, 'High Impact on the Environment'),
        (Medium, 'Medium Impact on the Environment'),
        (Low, 'Low Impact on the Environment'),
    ]
    user=models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title=models.CharField(max_length=250, null=True, blank=True)
    description=models.TextField(null=True,blank=True)
    complete=models.BooleanField(default=False)
    sustainability_rating = models.PositiveIntegerField(null=True, blank=True)
    energy_consumption = models.CharField(max_length=1, choices=IMPACT_CHOICES, default=High)
    carbon_footprint = models.CharField(max_length=1, choices=IMPACT_CHOICES, default=High)
    water_usage = models.CharField(max_length=1, choices=IMPACT_CHOICES, default=High)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering=['complete']

base/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task


class CustomeLoginView(LoginView):
    template_name='base/login.html'
    fields= '__all__'
    redirect_authenticated_user= True

    def get_success_url(self):
        return reverse_lazy('tasks')
    
class RegisterPage(FormView):
    template_name= 'base/register.html'
    form_class= UserCreationForm
    redirect_authenticated_user= True
    success_url= reverse_lazy('tasks')

    def form_valid(self, form):
        user= form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self). form_valid(form)
    
    def get(self, *arg, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super(RegisterPage, self).get(*arg, **kwargs)

 
class TaskList(LoginRequiredMixin, ListView):
    model= Task
    context_object_name='tasks'

    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['tasks']= context['tasks'].filter(user=self.request.user)
        context['count']= context['tasks'].filter(complete=False).count()

        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks']=context['tasks'].filter(title__startswith=search_input)

        context['search_input']=search_input
        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model= Task
    context_object_name='task'
    template_name='base/task.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    model= Task
    fields= ['title', 'description', 'complete']
    success_url= reverse_lazy('tasks')

    def form_valid(self, form):
        form.instance.user= self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model= Task
    fields= fields= ['title', 'description', 'complete']
    success_url= reverse_lazy('tasks')


class DeleteView(LoginRequiredMixin, DeleteView):
    model= Task
    context_object_name= 'task'
    success_url= reverse_lazy('tasks')

base/templates/base/login.html
{% extends 'base/main.html' %}
{% block content %}

<h1>Login</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Login">

</form>

<p> Don't have an account? <a href="{% url 'register' %}">Register</a></p>

{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>To DO ITEMS</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@1,200&display=swap" rel="stylesheet">

    <style>
        body{
            background-color: pink;
            font-family: 'Nunito Sans', sans-serif;
            padding-top: 50px;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6,
            {
                font-family: 'Raleway', sans-serif;
        }

        a,
        p {
            color: black;
        }

        




        .container{
            max-width: 550px;
            margin: auto;
            background-color: palevioletred;

        }

        .header-bar {
            background-color: plum;
            color: palevioletred; 
            display: flex; 
            justify-content: space-between; 
            align-items: center; 
            padding: 10px
        }
    </style>
    
</head>
<body>

    <div class="container">
        {% block content %}

        {% endblock content %}

    </div>
    
</body>
</html>

base/templates/base/register.html
{% extends 'base/main.html' %}
{% block content %}

<h1> Register </h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register">

</form>

<p> Already have an account? <a href="{% url 'login' %}">Login</a></p>

{% endblock content %}

base/templates/base/task.html
<h1> Task: {{task}}</h1>

base/templates/base/task_confirm_delete.html
{% extends 'base/main.html' %}
{% block content %}

<a href="{% url 'tasks' %}">Go Back</a>
<form method="POST">
    {% csrf_token %}
    <p>Are you Sure You want to delete this Task? "{{task}}"</p>
    <input type="submit"  value="Delete" />

</form>

{% endblock content %}

base/templates/base/task_form.html
{% extends 'base/main.html' %}
{% block content %}

<h3> Task Form </h3>
<a href="{% url 'tasks' %}">Go Back</a>

<form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}
    <div>
        <label for="id_energy_consumption">Energy Consumption:</label>
        <select id="id_energy_consumption" name="energy_consumption">
          <option value="{{ task.High }}">High Impact</option>
          <option value="{{ task.Medium }}">Medium Impact</option>
          <option value="{{ task.Low }}">Low Impact</option>
        </select>
      </div>
      <div>
        <label for="id_carbon_footprint">Carbon Footprint:</label>
        <select id="id_carbon_footprint" name="carbon_footprint">
          <option value="{{ task.High }}">High Impact</option>
          <option value="{{ task.Medium }}">Medium Impact</option>
          <option value="{{ task.Low }}">Low Impact</option>
        </select>
      </div>
      <div>
        <label for="id_water_usage">Water Usage:</label>
        <select id="id_water_usage" name="water_usage">
          <option value="{{ task.High }}">High Impact</option>
          <option value="{{ task.Medium }}">Medium Impact</option>
          <option value="{{ task.Low }}">Low Impact</option>
        </select>
      </div>
    <input type="submit" value="sumbit">
</form>

{% endblock content %}

base/templates/base/task_list.html
{% extends 'base/main.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <h1>Helloo {{ request.user|title }}</h1>
        <h3 style="margin:0">You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s" }} </h3>
    </div>
     {% if request.user.is_authenticated %}
     <a href="{% url 'logout' %}">Logout</a>
     {% else %}
     <a href="{% url 'login' %}">Login</a>
     {% endif %}

</div>




<hr>
<h1> My To Do List {{color}} </h1>
<a href="{% url 'task-create' %}">Add Task</a>
<form method="GET">
    <input type="text" name="search-area" value="{{search_input}}">
    <input type="submit" value="Search">
</form>

<table>
    <tr>
        <th>Item</th>
        <th></th>
        <th></th>
    </tr>
    {% for task in tasks %}
    <tr>
        <td>{{task.title}}</td>
        <td><a href="{% url 'task' task.id %}">View</a></td>
        <td><a href="{% url 'task-update' task.id %}">Edit</a></td>
        <td><a href="{% url 'task-delete' task.id %}">Delete</a></td>
        
    </tr>
    {% empty %}
    <h3>No items in list</h3>

    {% endfor %}
</table>

{% endblock content %}